version: "3.7"
services:
  php:
    build:
      context: .
    volumes:
      - remote-workspace:/workspace
    command: apache2-foreground
    ports:
      - 8088:80
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=codeigniter
      - MYSQL_DATABASE=ci4
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  remote-workspace: